#!/bin/csh 

set VERSION=2015.0

echo ' '
echo 'Testing ktools'
echo ' '
date

echo 'Running  ktools'
../ktools hono2.dat
echo 'done'

#! Remove large output files
rm *dens
rm *sums
rm *kej

echo ' ' 
echo -n 'Would you like to compare the output versus the test output? [y/n]?'
 set response=$<
	if $response == 'y' then
	else
	echo 'Finished'
	exit
	endif
echo ''

echo 'Running diff'

diff -s hono2.canonical hono2.canonical.test

echo 'Finished'
echo ' '



