#!/bin/csh

set VERSION=2021.0

echo ' '
echo 'Testing paradensum'
date

echo ' '
echo 'Running paradensum ... this takes a few minutes'
echo ' '
mpirun -np 4 ../paradensum
echo 'done'

echo ' ' 
echo -n 'Would you like to compare the output versus the test output? [y/n]?'
 set response=$<
	if $response == 'y' then
	else
	echo 'Finished'
	exit
	endif
echo ''

echo 'Running diff'

diff paradensum.out paradensum.out.test

echo 'Finished'


