#!/bin/csh 

set VERSION=2015.0

echo ' '
echo 'Testing bdens'
echo ' '
date

echo 'Running  bdens'
../bdens
echo 'done'

echo ' ' 
echo -n 'Would you like to compare the output versus the test output? [y/n]?'
 set response=$<
	if $response == 'y' then
	else
	echo 'Finished'
	exit
	endif
echo ''

echo 'Running diff'

diff -s bdens.out bdens.out.test

echo 'Finished'
echo '***NOTE: bdens output may differ on 64 bit machines***'



