#!/bin/csh 

set VERSION=1.0

echo ' '
echo 'Testing MomInert'
date

set current=$PWD

echo 'Running mominert'
../mominert
echo 'done'

echo ' ' 
echo -n 'Would you like to compare the output versus the test output? [y/n]?'
 set response=$<
	if $response == 'y' then
	else
	echo 'Finished'
	exit
	endif
echo ''

echo 'Running diff'
echo ''

diff -s mominert.out mominert.out.test

echo ''
echo 'Finished'


